# This worflow deploys the smart contracts to the Optimistic Kovan testnet network.
name: CD Workflow

# Configure the workflow to run manually.
on:
  workflow_dispatch:

jobs:
  deploy-to-optimistic-kovan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: üì¶ Use Node.js v16.14.2 (LTS)
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
        cache: 'npm'
    - name: üîß Install dependencies
      run: npm install
    - name: üè† Deploy to a localhost blockchain
      run: npx hardhat run scripts/deploy.ts
    - name: üöÄ Deploy to Optimistic Kovan testnet
      run: npx hardhat run scripts/deploy.ts --network optimisticKovan
      continue-on-error: true # TODO: find out why it fails even though the verification succeeds.
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      OPTIMISTIC_KOVAN_URL: ${{ secrets.OPTIMISTIC_KOVAN_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
